[package]
name = "gitql"
authors = ["AmrDeveloper"]
version = "0.4.0"
edition = "2021"
description = "A SQL like query language to perform queries on .git files"
license = "MIT"
repository = "https://github.com/amrdeveloper/gql/"
documentation = "https://github.com/amrdeveloper/gql"
readme = "README.md"
keywords = ["cli", "gql", "language", "git", "sql"]
categories = ["command-line-utilities"]
exclude = [".github/**", "docs/**", "media/**", "scripts/**"]

[dependencies]
git2 = { version = "0.17.1", default-features = false }
regex = "1.8.4"
lazy_static = "1.4.0"
termcolor = "1.2.0"
prettytable-rs = "^0.10"
textwrap = "0.16.0"