[package]
name = "gql"
authors = ["AmrDeveloper"]
version = "0.1.0"
edition = "2021"
description = "Git query language"
license = "MIT"
repository = "https://github.com/amrdeveloper/gql"

[dependencies]
git2 = "0.17.1"
lazy_static = "1.4.0"