[package]
name = "gql"
authors = ["AmrDeveloper"]
version = "0.2.0"
edition = "2021"
description = "Git query language"
license = "MIT"
repository = "https://github.com/amrdeveloper/gql/"
readme = "README.md"
categories = ["command-line-utilities"]
exclude = [".github/**"]

[dependencies]
git2 = { version = "0.17.1", default-features = false }
regex = "1"
lazy_static = "1.4.0"
termcolor = "1.2.0"
prettytable-rs = "^0.10"
textwrap = "0.16.0"
openssl = { version = "0.10", features = ["vendored"] }